# .yarnrc.yml

# Use the node-modules linker (traditional node_modules structure)
nodeLinker: node-modules

# Enable or disable Plug'n'Play (PnP)
pnpMode: disabled

# Yarn version to use (you can specify a version or use 'latest')
# yarnPath: .yarn/releases/yarn-3.2.3.cjs

# Package management settings
enableGlobalCache: true

# Plugin settings (uncomment if you want to use plugins)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: "@yarnpkg/plugin-typescript"

# Registry settings (use npm registry by default)
npmRegistryServer: "https://registry.npmjs.org"

# Dependency hoisting settings
nmHoistingLimits: workspaces

# Workspace settings (if you're using a monorepo structure)
# workspaces:
#   - packages/*

# Enable or disable automatic installation of peer dependencies
# Note: This is enabled by default in Yarn 2+
# auto-install-peers: true

# Specify the default language for running scripts
defaultLanguageName: node

# Control Yarn's output verbosity
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard